return {
    {
        "folke/trouble.nvim",
        version = "^2.0.0",
        event = { "LspAttach" },
        dependencies = { "nvim-tree/nvim-web-devicons" },
        opts = {
            position = "bottom",
            height = 15,
            icons = true,
            mode = "document_diagnostics",
            fold_open = "",
            fold_closed = "",
            group = true,
            padding = false,
            action_keys = {
                -- map to {} to remove a mapping, for example:
                -- close = {},
                close = "q",
                cancel = "<esc>",
                refresh = "r",
                jump = { "<cr>", "l" },
                open_split = {},
                open_vsplit = {},
                open_tab = {},
                jump_close = { "o" },
                toggle_mode = {},
                toggle_preview = {},
                hover = {},
                preview = "p",
                close_folds = { "W" },
                open_folds = { "E" },
                toggle_fold = { "h" },
                previous = "k",
                next = "j",
            },
            indent_lines = false,
            auto_open = false,
            auto_close = true,
            auto_preview = true,
            auto_fold = false,
            auto_jump = { "lsp_definitions" },
            signs = {
                other = "",
            },
            use_diagnostic_signs = true,
        },
    },
    {
        "folke/todo-comments.nvim",
        version = "^1.0.0",
        event = { "BufReadPre", "BufNewFile" },
        dependencies = { "nvim-lua/plenary.nvim" },
        opts = {
            signs = true,
            keywords = {
                TODO = { icon = " ", color = "info" },
                REFACTOR = { icon = "פֿ ", color = "warning" },
                FIXME = { icon = " ", color = "error" },
            },
            colors = {
                error = { "DiagnosticError" },
                warning = { "DiagnosticWarn" },
                info = { "DiagnosticInfo" },
                hint = { "DiagnosticHint" },
            },
            gui_style = {
                fg = "NONE",
                bg = "BOLD",
            },
        },
    },
}
